apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: saravanan777/invman-backend:latest
        ports:
          - containerPort: 3000
        env:
          - name: DB_HOST
            value: postgres
          - name: DB_USER
            value: myuser
          - name: DB_PASSWORD
            value: mypassword
          - name: DB_NAME
            value: mydb
