default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'inv_man_development' %>

test:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'inv_man_test' %>

production:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'inv_man_production' %>

