name: Backend CI/CD Pipeline - Prod

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create master.key
        run: |
          mkdir -p config
          echo "${{ secrets.RAILS_MASTER_KEY }}" > config/master.key

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hotel-inventory-backend:${{ github.sha }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: prod-cluster
          location: ${{ secrets.GKE_ZONE }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Replace version tag in manifests
        run: |
          sed -i "s|<VERSION_TAG>|${{ github.sha }}|g" k8s/prod/backend-deployment.yml
          sed -i "s|<VERSION_TAG>|${{ github.sha }}|g" k8s/prod/backend-migrate-job.yml

      - name: Deploy to Kubernetes - service & deployment
        run: |
          kubectl apply -f k8s/prod/backend-service.yml --validate=false
          kubectl apply -f k8s/prod/backend-deployment.yml --validate=false

      - name: Run DB migrations
        run: |
          echo "Running DB migrations with image: saravanan777/hotel-inventory-backend:${{ github.sha }}"
          kubectl delete job backend-migrate --ignore-not-found
          kubectl apply -f k8s/prod/backend-migrate-job.yml --validate=false

      - name: Rollout restart backend deployment
        run: kubectl rollout restart deployment backend --namespace=default
